### ISSUE TITLE
Docs - Adding a MIT Licenses badge and a Licenses section in readme

### ISSUE THREAD

**Issue by 1Shubham7** [arakoodev/EdgeChains#157]
The readme file of the repo should have a Licenses badge and some text regarding licenses in the Licenses section to make it more professional.

![afters](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/116020663/df57e4ed-2b1c-4236-b95d-17c9f3190e5a)

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by sandys** [comment]
The readme file already has a mit license badge. Please see carefully. This
issue cannot be worked on because of that.
