### ISSUE TITLE
BOUNTY: fix hierarchical maven build

### ISSUE THREAD

**Issue by sandys** [arakoodev/EdgeChains#194]
We have raced ahead to add features and algorithms. We havent had time to code review.

**Describe your ideal solution**
* Try out edgechains (spring boot, rxjava, jbang, sjsonnet)
* One particular area of fix is fixing the build. Edgechains is built as a library jar, however, we dont have a nice single step hierarchical maven build. We need this fixed.
* your new build should run inside github actions (we already have automated build running) and all tests should run.
* add atleast 1 testcase to test sanity of your new library jar

P.S. if you hit any bugs or problems while using it, we will fix it.

This code review is only available to experienced java programmers. Please do not attempt this if your github does not show Java/maven expertise.

**Comment by Hrushi20** [comment]
Hey @sandys, I am a java programmer. I am thinking of creating a pom.xml file in [this](https://github.com/arakoodev/EdgeChains/tree/main/FlySpring) directory. I also thought of removing common dependencies and adding it to global pom.

Currently, each module is adding all the dependencies of other modules (Eg: Edgechain app pom.xml contains few dependencies of fly fly module). After hierarchical maven, we can just add the group id, artifactId of respective module. 

I am confident I can fix this issue. Thanks.

**Comment by robincakeellis** [comment]
Parent pom with dependencies would be possible.
