### ISSUE TITLE
BOUNTY: create a Javascript/Typescript equivalent of the Edgechains library

### ISSUE THREAD

**Issue by sandys** [arakoodev/EdgeChains#202]
The edgechains library is in Java - and basically does 3 things:
1. Execute jsonnet (https://jsonnet.org/) files
2. have a cli to run java files
3. some classes like GPT3Endpoint, GPT4Endpoint, SupabaseEndpoint, PineconeEndpoint to make it easy to connect to OpenAI or Supabase/Pinecone.
4. easy way to create apis (using classes).

Edgechains works beautifully and is used in production. We want you to replicate the same in Javascript. You dont have to invent anything - just replicate the same structure in Javascript/Typescript. As long as the jsonnet files execute in the same way, we will deem this project complete.

**Comment by Hrushi20** [comment]
/attempt #202

Can I be assigned to this

**Comment by sandys** [comment]
hi @Hrushi20 
we would assign this only after seeing some initial thoughts and proposal. Want to make sure you can pull this off. 
Hope you dont mind that.

**Comment by neo773** [comment]
@sandys 
Some thoughts
For `jsonnet` we could probably use use this lib [node-jsonnet](https://github.com/hanazuki/node-jsonnet)
For the CLI I suppose these are the [commands](https://github.com/arakoodev/EdgeChains/tree/6fe86df3d19e6ef90523e004217ef604a3fd1b4b/FlySpring/flyfly/src/main/java/com/flyspring/flyfly/commands/run)
For 3. & 4. could you elaborate more?

**Comment by sandys** [comment]
> @sandys Some thoughts For `jsonnet` we could probably use use this lib [node-jsonnet](https://github.com/hanazuki/node-jsonnet) For the CLI I suppose these are the [commands](https://github.com/arakoodev/EdgeChains/tree/6fe86df3d19e6ef90523e004217ef604a3fd1b4b/FlySpring/flyfly/src/main/java/com/flyspring/flyfly/commands/run) shouldn't be too hard to build a wrapper around those For 3. & 4. could you elaborate more?

https://github.com/arakoodev/EdgeChains/blob/main/Examples/postgresql/PostgreSQLExample.java#L41-L44

you will not be able to do this without running current java edgechains. how are you proposing to test the output ?

**Comment by neo773** [comment]
> > @sandys Some thoughts For `jsonnet` we could probably use use this lib [node-jsonnet](https://github.com/hanazuki/node-jsonnet) For the CLI I suppose these are the [commands](https://github.com/arakoodev/EdgeChains/tree/6fe86df3d19e6ef90523e004217ef604a3fd1b4b/FlySpring/flyfly/src/main/java/com/flyspring/flyfly/commands/run) shouldn't be too hard to build a wrapper around those For 3. & 4. could you elaborate more?
> 
> https://github.com/arakoodev/EdgeChains/blob/main/Examples/postgresql/PostgreSQLExample.java#L41-L44
> 
> you will not be able to do this without running current java edgechains. how are you proposing to test the output ?

To confirm, are you proposing a complete rewrite of the library in TypeScript? I initially understood that the bounty was specifically for developing the client library in TypeScript, while keeping the backend in Java.

**Comment by Hrushi20** [comment]
We can rewrite the required endpoints in typescript (OpenAiEndpoint,PostgresEndpoint etc). I didn't understand the 4th requirement.

**Comment by sandys** [comment]
> > > @sandys Some thoughts For `jsonnet` we could probably use use this lib [node-jsonnet](https://github.com/hanazuki/node-jsonnet) For the CLI I suppose these are the [commands](https://github.com/arakoodev/EdgeChains/tree/6fe86df3d19e6ef90523e004217ef604a3fd1b4b/FlySpring/flyfly/src/main/java/com/flyspring/flyfly/commands/run) shouldn't be too hard to build a wrapper around those For 3. & 4. could you elaborate more?
> > 
> > 
> > https://github.com/arakoodev/EdgeChains/blob/main/Examples/postgresql/PostgreSQLExample.java#L41-L44
> > you will not be able to do this without running current java edgechains. how are you proposing to test the output ?
> 
> To confirm, are you proposing a complete rewrite of the library in TypeScript? I initially understood that the bounty was specifically for developing the client library in TypeScript, while keeping the backend in Java.

yes it is a rewrite of the current library in typescript. NOT a client implementation. We dont have client implementation. We only provide rest endpoints.

**Comment by sandys** [comment]
> We can rewrite the required endpoints in typescript (OpenAiEndpoint,PostgresEndpoint etc). I didn't understand the 4th requirement.

you compose your final api (/my-cool-chatbot) which uses all these other classes and APIs internally. We should make that as nice as easy to work with as possible. Things to think about - how will a user write their business logic where they have to call the OpenAI endpoint with some prompts and then do chat with it ?

look at chain 1 to 6 here - https://github.com/arakoodev/EdgeChains/blob/main/Examples/supabase-miniLM/SupabaseMiniLMExample.java#L226-L270

**Comment by sandys** [comment]
> > We can rewrite the required endpoints in typescript (OpenAiEndpoint,PostgresEndpoint etc). I didn't understand the 4th requirement.
> 
> you compose your final api (/my-cool-chatbot) which uses all these other classes and APIs internally. We should make that as nice as easy to work with as possible. Things to think about - how will a user write their business logic where they have to call the OpenAI endpoint with some prompts and then do chat with it ?
> 
> look at chain 1 to 6 here - https://github.com/arakoodev/EdgeChains/blob/main/Examples/supabase-miniLM/SupabaseMiniLMExample.java#L226-L270

also a clarification - that im not advocating to follow the same code as java. In fact, i think it can be much much simpler and cleaner. Just pointing to the java file to give you an idea of how to think about the problem statement.

**Comment by ayewo** [comment]
Hi @Hrushi20,
It's been 3 weeks now without any activity so wondering if you will be able to open a PR in the next 24-48 hrs?

**Comment by Hrushi20** [comment]
Hey I got caught with other works. I'll raise a draft PR in 24-48hrs. Thanksss.

**Comment by ayewo** [comment]
@Hrushi20 it took you nearly a month just to reply that you were busy? 😁

I asked for a status update because I wanted to work on the issue. But like you, I've also been caught up on other stuff ...

I think there are at least two possible ways to approach the task of converting Java -> TS and since @sandys already remarked _"we would assign this only after seeing some initial thoughts and proposal. Want to make sure you can pull this off."_, I wanted to be confident in the approach I'm adopting before commenting with my `/attempt #202`. I'm providing this heads up just in case I do find time to work on this.

Good luck with raising a PR but I think it's better to assess the pros and cons of your approach (with @sandys) before writing any code. 

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cllxt6xlm0002mn0fezh4iy0a/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by sandys** [comment]
> @Hrushi20 it took you nearly a month just to reply that you were busy? 😁
> 
> I asked for a status update because I wanted to work on the issue. But like you, I've also been caught up on other stuff ...
> 
> I think there are at least two possible ways to approach the task of converting Java -> TS and since @sandys already remarked _"we would assign this only after seeing some initial thoughts and proposal. Want to make sure you can pull this off."_, I wanted to be confident in the approach I'm adopting before commenting with my `/attempt #202`. I'm providing this heads up just in case I do find time to work on this.
> 
> Good luck with raising a PR but I think it's better to assess the pros and cons of your approach (with @sandys) before writing any code.
> 
> Options

hi @ayewo we would love to see your thoughts here. the bounty is still open. I see that @Hrushi20 has opened a draft PR https://github.com/arakoodev/EdgeChains/pull/256 with no commits in them - happy to hear @Hrushi20 thoughts as well.

also want to mention that we already have progress on the TS SDK here - https://github.com/arakoodev/EdgeChains/tree/ts
we are not looking for a straight Java -> TS translation here, but rather keep the spirit of edgechains while leveraging TS (and the larger JS ecosystem). we have been thinking of a WinterCG/Honojs/Elysiajs based SDK with ESBuild based system .
But the bare minimum SDK is already ready.

But happy to hear thoughts. @ayewo if you want to discuss on a call , happy to do so. 

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cllxt6xlm0002mn0fezh4iy0a/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by ayewo** [comment]
@sandys thanks for the heads up on the progress you've made with the TS SDK.

As I said, If I do find time to work on this, then yes, I'll definitely be up for a discussion.

**Comment by MohakBajaj** [comment]
/attempt #202

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cllxt6xlm0002mn0fezh4iy0a/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by sandys** [comment]
closing

https://www.npmjs.com/package/@arakoodev/edgechains.js

**Comment by realmpastai-web** [comment]
Hi! I would like to work on this $500 bounty. I have experience with TypeScript, OpenAI APIs, and CLI tooling. I have already forked the repo to realmpastai-web/EdgeChains-JS and will start implementing the JavaScript/TypeScript port immediately. ETA: 3-5 days. /attempt #202
