### ISSUE TITLE
BOUNTY: create an example+blogpost that implements PDF indexing and chatbot search using supabase

### ISSUE THREAD

**Issue by sandys** [arakoodev/EdgeChains#203]
we want someone to create a semantic search chatbot example using EdgeChains. Please note that we have verified that this ALREADY works perfectly in lots of teams that are using EdgeChains. However is closed source.
We want someone from the community to contribute a working example.

The following features are needed:
1. Parsing of PDF and chunking.
2. Creating embeddings (using BGE embedder and Ada002 - both of which are properly supported by EdgeChains). Embeddings must be created in parallel.
3. Store these embeddings in a Supabase PGVector based vector db. 
4. Augment embeddings using some extra metadata using metadata tables (metadata tables are a functionality already implemented in EdgeChains)
5. Search using COSINE/INNER-PRODUCT search
6. create HTMX based UI (already implemented https://github.com/arakoodev/EdgeChains/tree/main/Examples/htmx-ui-demo)
7. write a README that explains every line of the example. this is the most important part and this is why this bounty exists. We will publish this as a blog post, so must be sufficiently detailed.

you can message us on discord and we will help you to the most extent possible. Nothing in here is unknown and we have verified these usecases already work.

**Comment by rishi-raj-jain** [comment]
Damn so much for 25

**Comment by abhinavsaurav** [comment]
This is way too much work for 25 dollars. Every point looks like its own feature.

**Comment by sandys** [comment]
feature ? 

oh - it seems u have not run the examples. but maybe its my fault for not explaining clearly that all the features above are already implemented and in the examples already. 

for e.g. - here's ur PDF reader functionality - https://github.com/arakoodev/EdgeChains/blob/main/Examples/supabase-miniLM/SupabaseMiniLMExample.java#L161

but of course, it is easy to skip that by not reading examples! completely ok. Invite you to try again. But respect your choice that the examples may not be your cup of tea.

**Comment by TanmayDhobale** [comment]
@sandys i am working on ur issue .

**Comment by pritish45** [comment]
/attempt #203

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cllxvlhud0006mg0fdv6tm5fm/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by sandys** [comment]
done and completed
