### ISSUE TITLE
BOUNTY: Fix dual build (java & javascript) using Github Actions

### ISSUE THREAD

**Issue by sandys** [arakoodev/EdgeChains#272]
We have a perfectly working build system for the java code:
- release build https://github.com/arakoodev/EdgeChains/blob/main/.github/workflows/BuildAndRun.yml
- PR build https://github.com/arakoodev/EdgeChains/blob/main/.github/workflows/pr-build.yml

Our "ts" branch (https://github.com/arakoodev/edgechains/tree/ts) has both the Javascript code as well as the Java code. In this branch, i want build steps to run for java **OR** javascript based on the commit.
I have already fixed some preliminary build steps for the javascript code (https://github.com/arakoodev/EdgeChains/blob/ts/.github/workflows/prettier-js-format.yml), but it is not complete.

What will be considered project complete:
1. Release build actions for Java and Javascript separately. This is triggered by hand and not automatically. The Java action can be taken from here and modified (https://github.com/arakoodev/EdgeChains/blob/main/.github/workflows/BuildAndRun.yml). Javascript one may need some incremental work to create a npmjs package (https://github.com/arakoodev/EdgeChains/blob/ts/.github/workflows/prettier-js-format.yml)
2. When creating a PR, we also build. The java side build works perfectly (https://github.com/arakoodev/EdgeChains/blob/main/.github/workflows/pr-build.yml), and we have not yet created a javascript side one. However you should be able to copy the same config from the point above and make it work. WARNING: the PR build must build Java or Javascript based on commit path - meaning if code has been committed in the Java dir, then build Java code. If committed to JS directory, then build the Javascript code. If committed to both, then build both.

**Comment by ezhil56x** [comment]
Hello @sandys 👋🏻
Can I get this assigned?
/attempt #272

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clpfsnvh20002l90fdtqsvblg/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by sandys** [comment]
@ezhil56x assigned. best wishes.

**Comment by nermalcat69** [comment]
/attempt #272

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clpfsnvh20002l90fdtqsvblg/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by ezhil56x** [comment]
@sandys

What is the expected behaviour after formatting the JS on release workflow and in pr workflow?

**Comment by sandys** [comment]
Hi
Thank you for working on this.

Both the workflows have to do linting, formatting (prettifier) and then run
tests

(Do note that edgechains is a npm package, so u might have to do the
equivalent of npm link to run the tests).

Last step will be npm pack and it will upload a tar to the GitHub actions
output

https://dev.to/scooperdev/use-npm-pack-to-test-your-packages-locally-486e

**Comment by ezhil56x** [comment]
@sandys
I hope required changes are correctly implemented. If there are any changes to make, happy to do!

**Comment by sandys** [comment]
@ezhil56x we have added a comment to verify the erroneous merge. please also point to test runs on ur repo so we can test the builds before we accept this merge. 
we will be holding till then.

**Comment by ezhil56x** [comment]
@sandys For Js release should I run npm build and pack from JS/edgechains/lib? Is that correct

**Comment by Harsh4902** [comment]
@ezhil56x yes

**Comment by ezhil56x** [comment]
I have executed the below from `ts` branch JS/edgechains/lib
`npm i`
`npm run build`

And I'm getting the below error

src/lib/clients/PostgresClient.ts(1,46): error TS2307: Cannot find module 'typeorm' or its corresponding type declarations.

Error: Compiled with errors
TypeScript compilation or index.d.ts generation failed.

How to overcome this?

**Comment by ezhil56x** [comment]
@sandys I have opened a new pull request. I hope everything will work as expected now. If anything is to be changed, happy to do!

**Comment by sandys** [comment]
bounty paid. Thanks for your work @ezhil56x !
