### ISSUE TITLE
BOUNTY: add support for playwright (using jsonnet) for RPA using GPT

### ISSUE THREAD

**Issue by sandys** [arakoodev/EdgeChains#280]
generative AI can be used to do some automation activities - what is called as RPA.
Some examples are like what robocorp does - https://robocorp.com/portal/robot/robocorp/example-chatgpt-xpath-guesser-assistant
https://robocorp.com/portal/robot/ekipalen/RPA.OpenAI-Triviaplaza

we want similar functionality in Edgechains.js (javascript SDK - https://github.com/arakoodev/EdgeChains/tree/ts/JS/edgechains ) using https://playwright.dev/ SDK.
We use jsonnet to setup configuration for chatgpt/gpt api. for example we give prompts and even execute loops using jsonnet  - https://github.com/arakoodev/EdgeChains/blob/main/Examples/react-chain/react-chain.jsonnet
jsonnet is a well known configuration language - https://jsonnet.org/

this project will be deemed complete if:
1. you are able to give a declarative configuration in a jsonnet file on the activities to be performed (including xpaths, what buttons to be clicked, etc etc)
2. edgechains.js executes those actions using playwright.dev sdk.
3. the example to get working is the same as above  ( https://robocorp.com/portal/robot/robocorp/example-chatgpt-xpath-guesser-assistant and  https://robocorp.com/portal/robot/ekipalen/RPA.OpenAI-Triviaplaza)

**Comment by haruncurak** [comment]
Very happy to work on this one! Could you assign me? 
/attempt #280


<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clpl4szey000el50flzd61cg4/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by sandys** [comment]
@haruncurak just double checking that you would be comfortable to execute this bounty - since this is in typescript ? playwright.dev is a headless browser runner, etc
is this something you feel comfortable pulling off ?

**Comment by Gmin2** [comment]
@sandys can i take this?

**Comment by sandys** [comment]
@Min2who ur assigned to https://github.com/arakoodev/EdgeChains/issues/279 . if u want to take this, ull need to drop that one.

**Comment by haruncurak** [comment]
Hey @sandys, yeah! Got TS experience under my belt, looking through the codebase atm.

**Comment by Gmin2** [comment]
go ahead @haruncurak

**Comment by sandys** [comment]
@haruncurak assigned to you. if at any moment, u want to change that...please comment here.

**Comment by sandys** [comment]
@haruncurak if u need to discuss, please feel free to jump into discord. https://discord.gg/ZXahYqQE

**Comment by haruncurak** [comment]
Oops removed assign by accident

**Comment by sandys** [comment]
@haruncurak need any help ?

**Comment by haruncurak** [comment]
Hey @sandys I'll let you know! Currently prototyping. One question I do have is about where you want this stuff to be - I was thinking to create 2 more examples in the examples folder with the Playwright integration.

**Comment by sandys** [comment]
@haruncurak so ur right that the examples folder is the right place for examples. but since this is being driven using jsonnet configuration, i have a feeling u will need to create some core classes to add support. that will go inside the edgechains lib.

**Comment by haruncurak** [comment]
Understood. I've been able to get it working without having to add additional core classes with the following JSONNET. Do you have any more specific ideas for what kinds of core classes you think might be needed?  
```

{
  url: "https://www.triviaplaza.com/king-arthur-quiz/",
  playButtonSelector: "//a[contains(text(),'Play')]",
  questionSelector: "//div[@id='ques']",
  answerSelectors: {
    "A": "//div[@id='b1']",
    "B": "//div[@id='b2']",
    "C": "//div[@id='b3']",
    "D": "//div[@id='b4']"
  },
  maxQuestions: 10,
  gptModel: "gpt-3.5-turbo",

  // Custom prompt template for the quiz
  quizPromptTemplate: |||
    Given the following question and multiple-choice answers, determine the most likely correct answer.
    Question: {}
    A: {}
    B: {}
    C: {}
    D: {}
    The most likely correct answer is:
  |||,
}

```

**Comment by sandys** [comment]
that is great to know. however edgechains is a dev tool SDK. the idea is
for you to let others create these kind of flows very easily.
so we need the jsonnet integration (as was mentioned in the first part of
the issue).

secondly the playwright code will be driven by generative ai (which is the
openai integration we already have)

you seem to have built a demo application of pure playwright. that does not
solve the problem of our integration needs as party of this bounty :(

**Comment by haruncurak** [comment]
Ah understood, thanks for explaining what you meant @sandys. I think I'll be a bit pressed for time over the next couple of days so feel free to assign this to @Min2who or others who might be interested. Dropping it for now - sorry about that.

**Comment by sandys** [comment]
@haruncurak acknowledged. please cancel ur attempt (using the link in https://github.com/arakoodev/EdgeChains/issues/280#issuecomment-1833737867) so others can pick up

**Comment by haruncurak** [comment]
Done, thanks!

**Comment by sandys** [comment]
bounty closed and assigned separately.
