### ISSUE TITLE
BOUNTY: add webassembly build test (javy+wasmtime) to Github actions

### ISSUE THREAD

**Issue by sandys** [arakoodev/EdgeChains#282]
this bounty is for the javascript SDK only - https://github.com/arakoodev/EdgeChains/tree/ts/JS/edgechains
the existing github actions are here - https://github.com/arakoodev/EdgeChains/tree/ts/.github/workflows

we have used honojs for edgechains. this largely guarantees compatibility with webassembly compile. however it is *possible* you may have to add WASI modules to get honojs to build (e.g. https://github.com/bytecodealliance/javy/issues/386). But this shouldnt be too hard.

this project will be deemed complete if:
1. add a github action that:
    1.1. compiles javy and wasmtime from source.
    1.2 adds any missing wasi modules while compiling
    1.3 caches it in github actions (this is important)
2. for each example in https://github.com/arakoodev/EdgeChains/tree/ts/JS/edgechains/examples, it bundles, compiles-to-wasm (using javy) and runs using wasmtime.
3. each successful or failed compile+run is visible in the github actions logs.  

P.S. make sure your github action only runs on "ts" branch and only if a commit is made inside "JS" folder (not java)

**Comment by ezhil56x** [comment]
@sandys Can I give this a try?

**Comment by sandys** [comment]
@ezhil56x assigned. best wishes. 
take a look at some of the examples on github for setting up and using javy+wasmtime (e.g. https://github.com/surki/wasmtime-hello/blob/b53fd0c3c519cfe04fd5a7501c20a821429bd93b/js-wasm-hello-world/Makefile#L2)

**Comment by ezhil56x** [comment]
> @ezhil56x assigned. best wishes. 
> take a look at some of the examples on github for setting up and using javy+wasmtime (e.g. https://github.com/surki/wasmtime-hello/blob/b53fd0c3c519cfe04fd5a7501c20a821429bd93b/js-wasm-hello-world/Makefile#L2)

Should I run `javy compile index.js -o index.wasm`and then `wasmtime run index.wasm`for all the .js files in the examples folder. Is that the expected outcome. If not can you explain a bit on compiles-to-wasm (using javy) and runs using wasmtime

**Comment by sandys** [comment]
@ezhil56x yes pretty much. except that you have to build javy and wasmtime from source (as part of build process) **AND** add any missing wasi modules to make the compilation work.

**Comment by ezhil56x** [comment]
@sandys 

- Caching works for both Javy and Wasmtime installations
- Able to compile all .js files in the examples folder to .wasm

When I run `wasmtime run $filename`, I'm getting this error. Rest all works fine

[.github/workflows/webassembly.yml](https://github.com/ezhil56x/ec/blob/ts/.github/workflows/webassembly.yml)

[Test Action](https://github.com/ezhil56x/ec/actions/runs/7065561648/job/19235819219)

I have tested caching, it works as expected before adding compile with `javy` and run with `wasmtime`.

```
Error: failed to run main module `./dist/src/testGeneration/TestGenerator.wasm`

Caused by:
    0: failed to invoke command default
    1: error while executing at wasm backtrace:
           0: 0x5c6f1 - <unknown>!<wasm function 102>
           1: 0x71c9b - <unknown>!<wasm function 174>
           2: 0xb5002 - <unknown>!<wasm function 983>
    2: wasm trap: wasm `unreachable` instruction executed
Error: Process completed with exit code [13](https://github.com/ezhil56x/ec/actions/runs/7065561648/job/19235819219#step:11:14)4.
```

I'm stuck here. It would be great if you can help!

**Comment by rahul007-bit** [comment]
@ezhil56x 
The error you're experiencing is due to a missing feature in Javy like path, env, and a few other modules. I'm currently working on implementing this feature and expect it to be available in a few days. As soon as it's done I will message you.

**Comment by ezhil56x** [comment]
> @ezhil56x The error you're experiencing is due to a missing feature in Javy like path, env, and a few other modules. I'm currently working on implementing this feature and expect it to be available in a few days. As soon as it's done I will message you.

Javy and Wasmtime has been setup correctly. Currently it looks for all .wasm files in the examples folder and its subfolders and runs it using wasmtime

@sandys It would be great if you can share resource to compile a node project into wasm using javy

**Comment by sandys** [comment]
@ezhil56x we are going to update you with a fix for the wasm build in a few days. once that happens, u can fix ur integration.

if it doesnt happen, we will accept and award you this bounty. we will accept a cleanly documented PR for that with best attempt.
hope that is ok with you 😄

**Comment by ezhil56x** [comment]
> @ezhil56x we are going to update you with a fix for the wasm build in a few days. once that happens, u can fix ur integration.
> 
> if it doesnt happen, we will accept and award you this bounty. we will accept a cleanly documented PR for that with best attempt.
> hope that is ok with you 😄 

Yeah, I'm ok with that

**Comment by ezhil56x** [comment]
Any update on this @sandys

**Comment by rahul007-bit** [comment]
Here is the short [video](https://www.veed.io/view/e2d75b6f-048d-41f0-8c32-c5c1e4d0e37a) on work to set up our runtime and run an example Honojs application and I have also attach the zip below.

and these are the commands that I have used in the above video

```bash
apt install curl build-essential pkg-config libssl-dev nodejs npm clang libclang-dev -y
npm install -g @go-task/cli
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh # you can also rustup from apt repo
source $HOME/.cargo/env
```

[runtime.zip](https://github.com/arakoodev/EdgeChains/files/13663453/runtime.zip)
[video](https://www.veed.io/view/e2d75b6f-048d-41f0-8c32-c5c1e4d0e37a)

**Comment by ezhil56x** [comment]
/attempt #282

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clplcsnfl0002la0ftzxq1xjx/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by sandys** [comment]
bounty claim accepted. congratulations @ezhil56x

**Comment by sandys** [comment]
@ezhil56x would u be able to check quickly and suggest why the wasm build did not run on https://github.com/arakoodev/EdgeChains/pull/298

**Comment by ezhil56x** [comment]
@sandys 

Wasm build will only run when there is a change in `JS/wasm` folder. If required I can change it to `JS/` folder, then all changes in `JS/` folder the wasm build will be triggered

**Comment by sandys** [comment]
ah yes. it should be any file in JS

**Comment by ezhil56x** [comment]
Created a PR #299 that fixes the issue

**Comment by sandys** [comment]
Awesome, thanks for the update!
