### ISSUE TITLE
call huggingface embeddings from Java

### ISSUE THREAD

**Issue by sandys** [arakoodev/EdgeChains#29]
model to use - https://huggingface.co/sentence-transformers/all-MiniLM-L6-v1

java example - https://pub.towardsai.net/running-an-nlp-task-or-machine-learning-model-from-huggingface-in-java-8a3c7c131c10

**Comment by sandys** [comment]
https://pub.towardsai.net/deploy-huggingface-nlp-models-in-java-with-deep-java-library-e36c635b2053

**Comment by Adja002** [comment]
Could you please elaborate on this?

**Comment by Jawn78** [comment]
You could use OnnxRuntime. 
https://pub.towardsai.net/running-an-nlp-task-or-machine-learning-model-from-huggingface-in-java-8a3c7c131c10

**Comment by sandys** [comment]
@Jawn78 thanks for highlighting this. this is already done and working. we use it in production quite well!

e.g. https://github.com/arakoodev/EdgeChains/blob/6b893a1c114d8f06de0d2b3f5aa8effb2930d264/FlySpring/edgechain-app/src/main/java/com/edgechain/lib/embeddings/bgeSmall/BgeSmallClient.java#L101
