### ISSUE TITLE
Implement AutoGPT like langchain

### ISSUE THREAD

**Issue by Saatvik-droid** [arakoodev/EdgeChains#33]
https://python.langchain.com/en/latest/use_cases/autonomous_agents/autogpt.html

Completed

**Comment by Saatvik-droid** [comment]
[AutoGPT.py.md](https://github.com/arakoodev/EdgeChains/files/11448466/AutoGPT.py.md)

**Comment by yamadivya** [comment]
What is expected here @Saatvik-droid ?

**Comment by Saatvik-droid** [comment]
A basic AutoGPT implementation as seen in the link

**Comment by ayesha-firdaus** [comment]
Can I work on it?

**Comment by sandys** [comment]
hi this implementation is finished. thank you for your excitement ! please feel free to take any of the other issues!
