### ISSUE TITLE
add readme badges 

### ISSUE THREAD

**Issue by S-ishita** [arakoodev/EdgeChains#41]
i want to add readme badges. .Please assign this issue to me under GSSOC
![badges](https://github.com/arakoodev/EdgeChains/assets/104543751/489a239c-a230-44b8-9345-c9dedcbe19e9)

**Comment by sandys** [comment]
@S-ishita please feel free to take this issue. i dont have control over GSSOC internal procedures.

**Comment by S-ishita** [comment]
does this mean i can work on this issue?
if yes, please add me as assignee

**Comment by Pranav-Rayaprolu** [comment]
hey i would like to work on the project

**Comment by sandys** [comment]
completed and closed
