### ISSUE TITLE
Light Mode: There is no light mode option 

### ISSUE THREAD

**Issue by SagarSharma2809** [arakoodev/EdgeChains#48]
Many people prefer light mode and the website is made in dark mode as default. I can create a design for the light mode. Everything else will remain same just the color scheme will change that can provide users the option of light or dark mode on the website landing page.    After creating the light mode design, a toggle button will also be required so I can work on that too or create a new issue for that

GSSOC'23

**Comment by khushi767** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by sandys** [comment]
@SagarSharma2809 the repo for website work is https://github.com/arakoodev/doc

please open the issue there. This repo is only for the AI/ML sdk. closing this issue with thanks.
