### ISSUE TITLE
Fix Grammar in README

### ISSUE THREAD

**Issue by Sriparno08** [arakoodev/EdgeChains#51]
I have noticed some grammatical errors in README.

> This project hopes and requests for clean pull request merges. the way we merge is squash and merge. This fundamentally can only work if you NEVER ISSUE A PULL REQUEST TWICE FROM THE SAME LOCAL BRANCH. If you create another pull request from same local branch, then the merge will always fail.
>
> solution is simple - ONE BRANCH PER PULL REQUEST. We Follow this strictly. if you have created this pull request using your master/main branch, then follow these steps to fix it:

Fixes:

`hopes` -> `hopes for`
`requests for` -> `requests`
`the way we merge` -> `The method which we use for merging`
`solution` -> `The solution`
`Follow` -> `follow`
`if` -> `If`

**Comment by Sriparno08** [comment]
I would like to work on this as part of GSSoC'23.

**Comment by sandys** [comment]
grammatical error fixes are not not included in this repo as part of gssoc. please file issues on https://github.com/arakoodev/doc - this is our documentation repository and we welcome all kinds of grammatical and documentation fixes there.

closing with thanks
