### ISSUE TITLE
Missing Contributing.md file

### ISSUE THREAD

**Issue by Anshika-Jain02** [arakoodev/EdgeChains#76]
*Missing Contributing guidelines file in the repo to provide clear guidelines to the contributors. I can add it*

Please assign me this issue under Gssoc'23 @sandys

**Comment by RohanMishra315** [comment]
hey sandip pls assign me this issue . I can add contributors guidelines for the contributors

**Comment by sandys** [comment]
closing issue. please check readme for contributing guidelines already mentioned.
